name: Post Publish

on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  post_publish:
    name: Post Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check Publishable
        run: |
          pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}\\s.*"
          if [[ ! "${{ github.event.issue.title }}" =~ $pattern ]]; then
            echo "::cancel-job:: Issue title does not start with YYYY-MM-DD pattern. Ignored"
          fi
