name: Post Publish

permissions:
  actions: write

on:
  issues:
    types:
      - milestoned

jobs:
  post_publish:
    name: Post Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-node@v3
      - name: Issue To Post
        run: |
          npm install
          issue_data="${{toJson(github.event.issue)}}"
          node .github/workflows/issue_to_post.js "${issue_data}"
          git add .
          git commit -m "Publish ${{github.event.issue.title}}"
          git push -f origin HEAD
