on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  post_publish:
    if: /^\d{4}-\d{2}-\d{2}\s.*?/.test(github.event.issue.title)
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world! ${{ github.event.issue.title }}'
      
