name: Post Publish

on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  post_publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check Publishable
        run: |
          if [[ ! "${{ github.event.issue.title }}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2} .*$ ]]; then
            echo "Issue title does not start with YYYY-MM-DD pattern. Exiting."
            exit 1
          fi
