name: Post Publish

on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  post_publish:
    name: Post Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check Publishable
        id: check_publishable
        run: |
          pattern="^[0-9]{4}-[0-9]{2}-[0-9]{2}\\s.*"
          if [[ ! "${{ github.event.issue.title }}" =~ $pattern ]]; then
            echo "::notice::Issue title does not start with YYYY-MM-DD pattern. Ignored"
            echo "should_publish=false" >> $GITHUB_OUTPUT
          fi
      - name: Cancel Workflows Action
        uses: potiuk/cancel-workflow-runs@v4_7
        if: steps.check_publishable.outputs.should_publish != 'false'
        with:
          cancelMode: self
          cancelFutureDuplicates: false
      - name: Echo Issue Title and Body
        run: |
          echo "Issue Title: ${{ github.event.issue.title }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
