name: Post Publish

on:
  issues:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled

jobs:
  post_publish:
    if: github.event.issue.title =~ /^\d{4}-\d{2}-\d{2}\s.*$/
    runs-on: ubuntu-latest
    steps:
      - run: echo 'hello world! ${{ github.event.issue.title }}'
      
